### PR TITLE
fix: null item in queue from podcast

### LINKED ISSUE #357: When trying to play a playlist full of podcasts, the website sometimes breaks
https://user-images.githubusercontent.com/70028633/232336632-fbab7051-4f42-4caf-acf3-cdbd244cd1a7.mp4

image

Steps to reproduce: 

- Search "podcast", and navigate to the "hot girl walk" playlist 
- Press the play all button, and view results. 
*This only occurs when not connected to an external Spotify instance, such as the official web-Spotify

### PR DESCRIPTION
**Pull request by claycrews2002**
- Resolves #357

### CODE REVIEW

File: components/Sidebar/panels/Queue/index.tsx [hunk 1]
```diff
@@ -36,7 +36,8 @@ const Queue = async () => {
             className="text-sm overflow-hidden text-ellipsis whitespace-nowrap"
           >
             <Link
-              href={`/app/track/${item.id}`}
+              // eslint-disable-next-line @typescript-eslint/no-unnecessary-condition
+              href={item === null ? `` : `/app/track/${item.id}`}
```
Comment (cravend) [inline components/Sidebar/panels/Queue/index.tsx:40]: This will still throw an error because of `item.name` right? May be better to filter the queue array (inside the `getQueue` func) by item !== null

**Review by cravend — CHANGES_REQUESTED** [review]

**Review by cravend — APPROVED** [review]
